sudo: required

services:
    - docker

before_install:
    - docker build -t zsh-image .
    - docker run --name zsh -d zsh-image

script:
    - docker exec -it zsh zsh -c "./install.sh"
    - docker exec -it zsh zsh -c "./deploy.sh"
    - docker exec -it zsh zsh -c "source ~/.zshenv && source ~/.zshrc"

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push odanado/zsh
    fi

notifications:
    email: false
