- name: Make config directory
  file:
    path: ~/.config
    state: directory


- name: List files
  shell: "ls {{ role_path }}/files"
  register: files
  changed_when: false


- name: Link config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
  with_items: "{{ files.stdout_lines }}"
