vscode_extensions:
  - eamodio.gitlens
  - editorconfig.editorconfig
  - dbaeumer.vscode-eslint
  - octref.vetur
  - prisma.vscode-graphql
  - mauve.terraform
  - vscoss.vscode-ansible
  - vscode-icons-team.vscode-icons
  - vscode-styled-components
  - ms-azuretools.vscode-docker
  - ms-ceintl.vscode-language-pack-ja
  - ms-vscode-remote.remote-containers
  - ms-vsliveshare.vsliveshare
  - juanblanco.solidity
  - william-voyek.vscode-nginx
  - ms-python.python
  - ms-vscode.cpptools
  - toba.vsfire
  - d9705996.perl-toolbox
  - toba.vsfire
  - wayou.vscode-todo-highlight
  - stylelint.vscode-stylelint
  - dzhavat.css-flexbox-cheatsheet
  - VisualStudioExptTeam.vscodeintellicode
  - exiasr.hadolint
  - ms-vscode.go