vscode_extensions:
  - axetroy.vscode-deno
  - d9705996.perl-toolbox
  - dbaeumer.vscode-eslint
  - dzhavat.css-flexbox-cheatsheet
  - eamodio.gitlens
  - editorconfig.editorconfig
  - exiasr.hadolint
  - golang.go
  - hashicorp.terraform
  - juanblanco.solidity
  - marcostazi.vs-code-vagrantfile
  - ms-azuretools.vscode-docker
  - ms-ceintl.vscode-language-pack-ja
  - ms-python.python
  - ms-vscode-remote.remote-containers
  - ms-vscode.cpptools
  - ms-vsliveshare.vsliveshare
  - octref.vetur
  - prisma.vscode-graphql
  - stylelint.vscode-stylelint
  - toba.vsfire
  - toba.vsfire
  - VisualStudioExptTeam.vscodeintellicode
  - vscode-icons-team.vscode-icons
  - vscode-styled-components
  - vscoss.vscode-ansible
  - wayou.vscode-todo-highlight
  - william-voyek.vscode-nginx
  - 42Crunch.vscode-openapi
  - Arjun.swagger-viewer
  - tintinweb.solidity-visual-auditor
