[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1

let g:go_fmt_command = "goimports"

autocmd FileType go nmap <buffer><Leader>gg <Plug>(go-def-tab)
autocmd FileType go nmap <buffer><Leader>g <Plug>(go-def)

autocmd FileType go :highlight goErr cterm=bold ctermfg=214
autocmd FileType go :match goErr /\<err\>/
'''
