[[plugins]]
repo = 'tell-k/vim-autopep8'
hook_add = '''
let g:autopep8_disable_show_diff = 1
autocmd FileType python map <buffer><Leader>cf :call Autopep8()<CR>
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
depends = 'Shougo/deoplete.nvim'
hook_add = '''
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#force_py_version = 3
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#smart_auto_mappings = 0
autocmd FileType python set completeopt-=preview
'''

[[plugins]]
repo='zchee/deoplete-jedi'
depends = 'Shougo/deoplete.nvim'
