- name: Make bin directory
  file:
    path: ~/.local/bin
    state: directory


- name: List files
  shell: "ls {{ role_path }}/files"
  register: files
  changed_when: false


- name: Link bin files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.local/bin/{{ item }}"
    state: link
  with_items: "{{ files.stdout_lines }}"
