- name: Make local bin directory
  file:
    path: "{{ cli.install_dir }}"
    state: directory

- name: Install
  shell: "{{ role_path }}/files/installer.sh {{ item.user }} {{ item.repo }} {{ cli.install_dir }}"
  args:
    creates: "{{ cli.install_dir }}/{{ item.repo }}"
  with_items: "{{ cli.golang }}"