- name: Stat anyenv
  stat:
    path: "{{ anyenv.install_dir }}"
  register: anyenv_dir

- name: Clone
  git:
    repo: "{{ anyenv.git_url }}"
    dest: "{{ anyenv.install_dir }}"
  when: not anyenv_dir.stat.exists

- name: Stat anyenv-install
  stat:
    path: ~/.config/anyenv/anyenv-install
  register: anyenv_install

- name: Init
  shell: yes | anyenv install --init
  environment:
    PATH: "{{ anyenv.install_dir | regex_replace('^~(.*)$', lookup('env', 'HOME') + '\\1') }}/bin:{{ lookup('env', 'PATH') }}"
  when: not anyenv_install.stat.exists

- name: Install plugins
  git: 
    repo: "{{ item }}"
    dest: "{{ anyenv.install_dir }}/plugins/{{ item | basename }}"
  environment:
    PATH: "{{ anyenv.install_dir | regex_replace('^~(.*)$', lookup('env', 'HOME') + '\\1') }}/bin:{{ lookup('env', 'PATH') }}"
  with_items: "{{ anyenv.plugins }}"

- name: Install environment
  shell: "anyenv install {{ item }}"
  args:
    creates: "{{ anyenv.install_dir }}/envs/{{ item }}"
  environment:
    PATH: "{{ anyenv.install_dir | regex_replace('^~(.*)$', lookup('env', 'HOME') + '\\1') }}/bin:{{ lookup('env', 'PATH') }}"
  with_items: "{{ anyenv.envs }}"

- name: Link default-packages
  file:
    src: "{{ role_path }}/files/nodenv-default-packages"
    dest: "{{ anyenv.install_dir }}/envs/nodenv/default-packages"
    state: link
