- name: Stat nodenv
  stat:
    path: ~/.anyenv/envs/nodenv
  register: nodenv

- name: Install nodenv
  shell: anyenv install nodenv
  when: not nodenv.stat.exists
  register: install_nodenv
  changed_when: install_nodenv.rc != 0