- name: List files
  shell: "ls -ap {{ role_path }}/files | grep -v /"
  register: files
  changed_when: false


- name: Link dotfiles
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items: "{{ files.stdout_lines }}"
