- name: Link .zshenv
  file:
    src: "{{ role_path }}/files/.zshenv"
    dest: ~/.zshenv
    state: link

- name: Make config directory
  file:
    path: ~/.config
    state: directory

- name: Link config files
  file:
    src: "{{ role_path }}/files"
    dest: "{{ config_dir }}"
    state: link

- name: Import zplug
  import_tasks: zplug.yml