- name: Include var
  include_vars: zplug.yml

- name: Stat zplug
  stat:
    path: "{{ zplug.install_dir }}"
  register: zplug_dir

- name: Clone zplug
  git:
    repo: "{{ zplug.git_url }}"
    dest: "{{ zplug.install_dir }}"
  when: not zplug_dir.stat.exists
