# https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Run brew bundle
  shell: brew bundle --file {{ role_path }}/files/Brewfile
  changed_when: false

- name: Setup anyenv
  shell: anyenv install --init
  changed_when: false
