name: macos-ci

on: [push]

jobs:
  ansible:

    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2
    - name: Remove .gitconfig
      run: rm ~/.gitconfig

    - name: Install Homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Install Ansible
      run: python -m pip install --user ansible
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Run setup
      run: ./setup.sh
      env:
        CI: CI
