name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: tmp
      run: cat ~/.gitconfig
    - name: Install Homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Install Ansible
      run: brew install ansible
    
    - name: Run setup
      run: ./setup.sh
