name: Ubuntu CI

on: [push]

jobs:
  ansible:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: Start container
      run: docker-compose up -d

    - name: Run setup.sh
      run: docker-compose exec -e CI=CI ansible ./setup.sh
    - name: Rerun setup.sh
      run: docker-compose exec -e CI=CI ansible ./setup.sh

    - name: Rmoev container
      run: docker-compose down -v