name: Ubuntu CI

on: [push]

jobs:
  ansible:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . -t ansible
    - name: Start container
      run: docker run --name ansible -v $PWD:/work -d ansible tail -f /dev/null

    - name: Run setup for ansilbe
      run: docker exec -t ansible ./scripts/setup/ansible.sh
    - name: Rerun setup for ansilbe
      run: docker exec -t ansible ./scripts/setup/ansible.sh

    - name: Run setup for zplug
      run: docker exec -t ansible ./scripts/setup/zplug.sh

    - name: Rmoev container
      run: docker rm -f ansible